#Requires -Version 5.1
<#
.SYNOPSIS
  Install the official Yggdrasil MSI and apply the hannover-primary settings.

.DESCRIPTION
  Downloads the current x64 MSI from the Yggdrasil GitHub releases, installs
  it, and merges config/overlay.json plus config/peers.txt into
  %ProgramData%\Yggdrasil\yggdrasil.conf. The private key is generated by
  the MSI (or yggdrasil.exe -genconf) on this PC and is never written into
  the git checkout.

  Windows overrides: AdminListen is tcp://localhost:9001 and IfName is
  Yggdrasil. Those differ from the Linux overlay because the Windows build
  uses a TCP admin socket and the default Wintun adapter name.

.PARAMETER Action
  Install (default), Configure, Status, or Uninstall.

.PARAMETER RemoveConfig
  With Uninstall, also delete %ProgramData%\Yggdrasil. That deletes the
  private key and the node's IPv6 address.
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [ValidateSet('Install', 'Configure', 'Status', 'Uninstall')]
    [string]$Action = 'Install',

    [switch]$RemoveConfig
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Script:RepoRoot = Split-Path -Parent $PSScriptRoot
$Script:OverlayPath = Join-Path $Script:RepoRoot 'config\overlay.json'
$Script:PeersPath = Join-Path $Script:RepoRoot 'config\peers.txt'
$Script:InstallDir = Join-Path $env:ProgramFiles 'Yggdrasil'
$Script:ExePath = Join-Path $Script:InstallDir 'yggdrasil.exe'
$Script:CtlPath = Join-Path $Script:InstallDir 'yggdrasilctl.exe'
$Script:ConfDir = Join-Path $env:ProgramData 'Yggdrasil'
$Script:ConfPath = Join-Path $Script:ConfDir 'yggdrasil.conf'
$Script:WindowsAdminListen = 'tcp://localhost:9001'
$Script:WindowsIfName = 'Yggdrasil'
$Script:Utf8 = New-Object System.Text.UTF8Encoding $false

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Confirm-ConfigOutsideRepository {
    param([Parameter(Mandatory = $true)][string]$Path)
    $full = [System.IO.Path]::GetFullPath($Path)
    $root = [System.IO.Path]::GetFullPath($Script:RepoRoot)
    $separator = [System.IO.Path]::DirectorySeparatorChar
    $prefix = $root.TrimEnd($separator) + $separator
    if ($full.Equals($root, [System.StringComparison]::OrdinalIgnoreCase) -or
        $full.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to write node secrets inside the repository: $full"
    }
}

function Read-Utf8Text {
    param([Parameter(Mandatory = $true)][string]$Path)
    return [System.IO.File]::ReadAllText($Path, $Script:Utf8)
}

function Format-JsonString {
    param([AllowEmptyString()][string]$Value)
    if ($null -eq $Value) {
        $Value = ''
    }
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escaped + '"'
}

function Format-JsonStringArray {
    param([string[]]$Values, [string]$Indent)
    if ($null -eq $Values -or $Values.Count -eq 0) {
        return '[]'
    }
    $lines = @()
    foreach ($value in $Values) {
        $lines += ($Indent + '  ' + (Format-JsonString $value))
    }
    return "[`r`n" + ($lines -join ",`r`n") + "`r`n" + $Indent + ']'
}

function Read-PeerUriList {
    param([Parameter(Mandatory = $true)][string]$Path)
    $peers = New-Object System.Collections.Generic.List[string]
    $lineNo = 0
    foreach ($raw in (Read-Utf8Text -Path $Path) -split "`r?`n") {
        $lineNo++
        $line = $raw.Trim()
        if ($line.Length -eq 0 -or $line.StartsWith('#')) {
            continue
        }
        if ($line -notmatch '^(tcp|tls|quic|ws|wss|socks|sockstls|unix)://\S+$') {
            throw "Invalid peer URI in ${Path}:${lineNo}: $line"
        }
        if (-not $peers.Contains($line)) {
            $peers.Add($line)
        }
    }
    if ($peers.Count -eq 0) {
        throw "No active peer URIs in $Path"
    }
    return $peers.ToArray()
}

function Read-NodeOverlay {
    $text = Read-Utf8Text -Path $Script:OverlayPath
    if ($text -match '"PrivateKey"\s*:') {
        throw "overlay.json must not contain PrivateKey"
    }
    $overlay = $text | ConvertFrom-Json
    if ($overlay.NodeInfo.name -ne 'hannover-primary') {
        throw 'overlay.json NodeInfo.name must be hannover-primary'
    }
    if ($overlay.NodeInfo.location -ne 'Hannover/DE') {
        throw 'overlay.json NodeInfo.location must be Hannover/DE'
    }
    return $overlay
}

function Get-YggdrasilIdentity {
    param(
        [Parameter(Mandatory = $true)][string]$Exe,
        [Parameter(Mandatory = $true)][string]$Path
    )
    Confirm-ConfigOutsideRepository -Path $Path
    $normalised = & $Exe '-normaliseconf' '-json' '-useconffile' $Path | Out-String
    if ($normalised -match '"PrivateKeyPath"\s*:\s*"([^"]+)"') {
        return @{ PrivateKeyPath = $Matches[1] }
    }
    if ($normalised -match '"PrivateKey"\s*:\s*"([0-9a-fA-F]{128})"') {
        return @{ PrivateKey = $Matches[1].ToLowerInvariant() }
    }
    throw 'The existing configuration has no usable private key. Refusing to invent one inside the repository.'
}

function ConvertTo-WindowsNodeConfig {
    param(
        $Overlay,
        [string[]]$Peers,
        [hashtable]$Identity
    )
    $listen = @()
    if ($null -ne $Overlay.Listen) {
        $listen = @($Overlay.Listen)
    }
    $allowed = @()
    if ($null -ne $Overlay.AllowedPublicKeys) {
        $allowed = @($Overlay.AllowedPublicKeys)
    }
    $multiLines = @()
    foreach ($item in @($Overlay.MulticastInterfaces)) {
        $beacon = 'false'
        $listenFlag = 'false'
        if ($item.Beacon) { $beacon = 'true' }
        if ($item.Listen) { $listenFlag = 'true' }
        $multiLines += @"
    {
      "Regex": $(Format-JsonString ([string]$item.Regex)),
      "Beacon": $beacon,
      "Listen": $listenFlag
    }
"@
    }
    $multiJson = "[`r`n" + ($multiLines -join ",`r`n") + "`r`n  ]"
    $nodePairs = @()
    foreach ($prop in $overlay.NodeInfo.PSObject.Properties) {
        $nodePairs += ('    ' + (Format-JsonString $prop.Name) + ': ' + (Format-JsonString ([string]$prop.Value)))
    }
    $nodeJson = "{`r`n" + ($nodePairs -join ",`r`n") + "`r`n  }"
    if ($Identity.ContainsKey('PrivateKeyPath')) {
        $identityJson = '"PrivateKeyPath": ' + (Format-JsonString $Identity.PrivateKeyPath)
    }
    else {
        $identityJson = '"PrivateKey": ' + (Format-JsonString $Identity.PrivateKey)
    }
    $privacy = 'false'
    if ($Overlay.NodeInfoPrivacy) { $privacy = 'true' }
    $ifMtu = [int]$Overlay.IfMTU
    return @"
{
  $identityJson,
  "Peers": $(Format-JsonStringArray -Values $Peers -Indent '  '),
  "Listen": $(Format-JsonStringArray -Values $listen -Indent '  '),
  "AdminListen": $(Format-JsonString $Script:WindowsAdminListen),
  "AllowedPublicKeys": $(Format-JsonStringArray -Values $allowed -Indent '  '),
  "MulticastInterfaces": $multiJson,
  "IfName": $(Format-JsonString $Script:WindowsIfName),
  "IfMTU": $ifMtu,
  "NodeInfoPrivacy": $privacy,
  "NodeInfo": $nodeJson
}
"@
}

function Write-WindowsNodeConfig {
    param([Parameter(Mandatory = $true)][string]$Json)
    Confirm-ConfigOutsideRepository -Path $Script:ConfPath
    if ($Json -notmatch '"PrivateKey"\s*:\s*"[0-9a-fA-F]{128}"' -and $Json -notmatch '"PrivateKeyPath"') {
        throw 'Refusing to write a configuration without a private key.'
    }
    New-Item -ItemType Directory -Force -Path $Script:ConfDir | Out-Null
    $temp = Join-Path $Script:ConfDir '.yggdrasil.conf.tmp'
    Confirm-ConfigOutsideRepository -Path $temp
    [System.IO.File]::WriteAllText($temp, $Json.Trim() + "`r`n", $Script:Utf8)
    Move-Item -LiteralPath $temp -Destination $Script:ConfPath -Force
}

function Update-YggdrasilNodeConfig {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param()
    if (-not $PSCmdlet.ShouldProcess($Script:ConfPath, 'Write Yggdrasil configuration')) {
        return
    }
    if (-not (Test-Path -LiteralPath $Script:ExePath)) {
        throw "yggdrasil.exe not found at $($Script:ExePath). Run -Action Install first."
    }
    if (-not (Test-Path -LiteralPath $Script:ConfPath)) {
        Confirm-ConfigOutsideRepository -Path $Script:ConfPath
        New-Item -ItemType Directory -Force -Path $Script:ConfDir | Out-Null
        $generated = & $Script:ExePath '-genconf' '-json' | Out-String
        [System.IO.File]::WriteAllText($Script:ConfPath, $generated, $Script:Utf8)
    }
    $overlay = Read-NodeOverlay
    $peers = Read-PeerUriList -Path $Script:PeersPath
    $identity = Get-YggdrasilIdentity -Exe $Script:ExePath -Path $Script:ConfPath
    $json = ConvertTo-WindowsNodeConfig -Overlay $overlay -Peers $peers -Identity $identity
    Write-WindowsNodeConfig -Json $json
    Write-Information "Konfiguration aktualisiert: $($Script:ConfPath)" -InformationAction Continue
    Write-Information "AdminListen: $($Script:WindowsAdminListen)" -InformationAction Continue
    Write-Information "IfName: $($Script:WindowsIfName)" -InformationAction Continue
}

function Get-LatestX64Msi {
    param([Parameter(Mandatory = $true)][string]$DestinationDirectory)
    $headers = @{
        'User-Agent' = 'hannover-primary'
        Accept       = 'application/vnd.github+json'
    }
    $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/yggdrasil-network/yggdrasil-go/releases/latest' -Headers $headers
    $asset = $release.assets | Where-Object { $_.name -match '^yggdrasil-.+-x64\.msi$' } | Select-Object -First 1
    if ($null -eq $asset) {
        throw 'No x64 MSI was found in the latest Yggdrasil release.'
    }
    New-Item -ItemType Directory -Force -Path $DestinationDirectory | Out-Null
    $out = Join-Path $DestinationDirectory $asset.name
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $out -UseBasicParsing
    $hash = Get-FileHash -Algorithm SHA256 -Path $out
    Write-Information "MSI: $($asset.name)" -InformationAction Continue
    Write-Information "SHA256: $($hash.Hash)" -InformationAction Continue
    return $out
}

function Install-YggdrasilMsi {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param([Parameter(Mandatory = $true)][string]$MsiPath)
    if (-not $PSCmdlet.ShouldProcess($MsiPath, 'Install Yggdrasil MSI')) {
        return
    }
    $msiexec = Join-Path $env:SystemRoot 'System32\msiexec.exe'
    $proc = Start-Process -FilePath $msiexec -ArgumentList @('/i', $MsiPath, '/qn', '/norestart') -Wait -PassThru
    if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
        throw "msiexec exited with $($proc.ExitCode)"
    }
}

function Restart-YggdrasilWindowsService {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param()
    if (-not $PSCmdlet.ShouldProcess('Yggdrasil', 'Restart service')) {
        return
    }
    $service = Get-Service -Name 'Yggdrasil' -ErrorAction SilentlyContinue
    if ($null -eq $service) {
        throw 'The Yggdrasil Windows service was not found.'
    }
    Restart-Service -Name 'Yggdrasil' -Force
    Write-Information 'Dienst Yggdrasil neu gestartet.' -InformationAction Continue
}

function Install-YggdrasilNode {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param()
    if (-not $PSCmdlet.ShouldProcess($Script:ConfPath, 'Install Yggdrasil and write node configuration')) {
        return
    }
    if (-not (Test-Path -LiteralPath $Script:ExePath)) {
        $downloadDir = Join-Path $env:TEMP 'hannover-primary'
        $msi = Get-LatestX64Msi -DestinationDirectory $downloadDir
        Install-YggdrasilMsi -MsiPath $msi
    }
    else {
        Write-Information 'Yggdrasil ist bereits installiert. Konfiguration wird aktualisiert.' -InformationAction Continue
    }
    $deadline = (Get-Date).AddSeconds(45)
    while (-not (Test-Path -LiteralPath $Script:ExePath) -and (Get-Date) -lt $deadline) {
        Start-Sleep -Seconds 1
    }
    if (-not (Test-Path -LiteralPath $Script:ExePath)) {
        throw "yggdrasil.exe was not installed at $($Script:ExePath)"
    }
    Update-YggdrasilNodeConfig
    Restart-YggdrasilWindowsService
}

function Get-YggdrasilUninstallEntry {
    $paths = @(
        'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
    )
    return Get-ItemProperty -Path $paths -ErrorAction SilentlyContinue |
        Where-Object { $_.DisplayName -like '*Yggdrasil*' } |
        Select-Object -First 1
}

function Uninstall-YggdrasilNode {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param([switch]$RemoveNodeConfig)
    if (-not $PSCmdlet.ShouldProcess('Yggdrasil', 'Uninstall')) {
        return
    }
    $entry = Get-YggdrasilUninstallEntry
    if ($null -eq $entry) {
        throw 'Yggdrasil does not appear to be installed.'
    }
    $msiexec = Join-Path $env:SystemRoot 'System32\msiexec.exe'
    $proc = Start-Process -FilePath $msiexec -ArgumentList @('/x', $entry.PSChildName, '/qn', '/norestart') -Wait -PassThru
    if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
        throw "msiexec /x exited with $($proc.ExitCode)"
    }
    if ($RemoveNodeConfig) {
        Confirm-ConfigOutsideRepository -Path $Script:ConfDir
        if (Test-Path -LiteralPath $Script:ConfDir) {
            Remove-Item -LiteralPath $Script:ConfDir -Recurse -Force
        }
        Write-Information 'Konfiguration geloescht. Die IPv6-Adresse dieses Knotens ist verloren.' -InformationAction Continue
    }
    else {
        Write-Information "Paket entfernt. $($Script:ConfPath) bleibt erhalten (privater Schluessel)." -InformationAction Continue
    }
}

function Get-YggdrasilNodeStatus {
    if (-not (Test-Path -LiteralPath $Script:CtlPath)) {
        Write-Output 'Status: down'
        Write-Output 'yggdrasilctl.exe wurde nicht gefunden.'
        exit 1
    }
    $service = Get-Service -Name 'Yggdrasil' -ErrorAction SilentlyContinue
    if ($null -ne $service) {
        Write-Output "Dienst: $($service.Status)"
    }
    $selfText = & $Script:CtlPath '-json' '-endpoint' $Script:WindowsAdminListen 'getSelf' | Out-String
    $peersText = & $Script:CtlPath '-json' '-endpoint' $Script:WindowsAdminListen 'getPeers' | Out-String
    try {
        $selfDoc = $selfText | ConvertFrom-Json
    }
    catch {
        Write-Output 'Status: down'
        Write-Output 'Der Knoten antwortet nicht auf dem Admin-Socket.'
        exit 1
    }
    if (-not $selfDoc.address -or -not $selfDoc.subnet -or -not $selfDoc.key) {
        Write-Output 'Status: down'
        Write-Output 'Der Knoten antwortet nicht auf dem Admin-Socket.'
        exit 1
    }
    try {
        $peersDoc = $peersText | ConvertFrom-Json
        $connected = @($peersDoc.peers | Where-Object { $_.up })
    }
    catch {
        Write-Output 'Status: aktiv, Peer-Liste nicht lesbar'
        Write-Output "IPv6-Adresse: $($selfDoc.address)"
        Write-Output "IPv6-Subnetz: $($selfDoc.subnet)"
        Write-Output "Oeffentlicher Schluessel: $($selfDoc.key)"
        exit 2
    }
    if ($connected.Count -eq 0) {
        Write-Output 'Status: aktiv, aber kein Peer verbunden'
    }
    else {
        Write-Output 'Status: aktiv'
    }
    Write-Output "IPv6-Adresse: $($selfDoc.address)"
    Write-Output "IPv6-Subnetz: $($selfDoc.subnet)"
    Write-Output "Oeffentlicher Schluessel: $($selfDoc.key)"
    Write-Output "Verbundene Peers ($($connected.Count)):"
    if ($connected.Count -eq 0) {
        Write-Output '  (keine)'
        exit 2
    }
    foreach ($peer in $connected) {
        Write-Output ("  - {0}  {1}" -f $peer.remote, $peer.address)
    }
    exit 0
}

if ($env:YGG_IMPORT_ONLY -eq '1') {
    return
}

if ($Action -eq 'Status') {
    Get-YggdrasilNodeStatus
}

if (-not (Test-IsAdministrator)) {
    throw 'Administrator rights are required. Start PowerShell as Administrator.'
}

switch ($Action) {
    'Install' { Install-YggdrasilNode }
    'Configure' {
        Update-YggdrasilNodeConfig
        Restart-YggdrasilWindowsService
    }
    'Uninstall' { Uninstall-YggdrasilNode -RemoveNodeConfig:$RemoveConfig }
}
